"""added cot models

Revision ID: 3559d5f4e2c5
Revises: 89a20bee65a5
Create Date: 2021-05-23 12:45:02.465528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3559d5f4e2c5'
down_revision = '89a20bee65a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cftccontract',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_cftccontract_uid'), 'cftccontract', ['uid'], unique=False)
    op.create_table('cftcreport',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_uid', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('non_commercial_long', sa.Float(), nullable=True),
    sa.Column('non_commercial_short', sa.Float(), nullable=True),
    sa.Column('non_commercial_spreads', sa.Float(), nullable=True),
    sa.Column('commercial_long', sa.Float(), nullable=True),
    sa.Column('commercial_short', sa.Float(), nullable=True),
    sa.Column('total_long', sa.Float(), nullable=True),
    sa.Column('total_short', sa.Float(), nullable=True),
    sa.Column('non_reportable_long', sa.Float(), nullable=True),
    sa.Column('non_reportable_short', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contract_uid'], ['cftccontract.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_cftcreport_uid'), 'cftcreport', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cftcreport_uid'), table_name='cftcreport')
    op.drop_table('cftcreport')
    op.drop_index(op.f('ix_cftccontract_uid'), table_name='cftccontract')
    op.drop_table('cftccontract')
    # ### end Alembic commands ###
