"""added all n ch

Revision ID: 5ba5b0faaf77
Revises: 3559d5f4e2c5
Create Date: 2021-05-23 21:35:44.403453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba5b0faaf77'
down_revision = '3559d5f4e2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cftcreport', sa.Column('commercial_long_ch', sa.Float(), nullable=True))
    op.add_column('cftcreport', sa.Column('commercial_short_ch', sa.Float(), nullable=True))
    op.add_column('cftcreport', sa.Column('non_commercial_long_ch', sa.Float(), nullable=True))
    op.add_column('cftcreport', sa.Column('non_commercial_short_ch', sa.Float(), nullable=True))
    op.add_column('cftcreport', sa.Column('non_commercial_spreads_ch', sa.Float(), nullable=True))
    op.add_column('cftcreport', sa.Column('non_reportable_long_ch', sa.Float(), nullable=True))
    op.add_column('cftcreport', sa.Column('non_reportable_short_ch', sa.Float(), nullable=True))
    op.add_column('cftcreport', sa.Column('open_interest_ch', sa.Float(), nullable=True))
    op.add_column('cftcreport', sa.Column('total_long_ch', sa.Float(), nullable=True))
    op.add_column('cftcreport', sa.Column('total_short_ch', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cftcreport', 'total_short_ch')
    op.drop_column('cftcreport', 'total_long_ch')
    op.drop_column('cftcreport', 'open_interest_ch')
    op.drop_column('cftcreport', 'non_reportable_short_ch')
    op.drop_column('cftcreport', 'non_reportable_long_ch')
    op.drop_column('cftcreport', 'non_commercial_spreads_ch')
    op.drop_column('cftcreport', 'non_commercial_short_ch')
    op.drop_column('cftcreport', 'non_commercial_long_ch')
    op.drop_column('cftcreport', 'commercial_short_ch')
    op.drop_column('cftcreport', 'commercial_long_ch')
    # ### end Alembic commands ###
